name: build_app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    container: nathanesau/github_actions:qt-win64s

    steps:
    - uses: actions/checkout@v2
    - name: Building Windows x64 static
      run: ls && cd ${GITHUB_WORKSPACE}/src/app/cpp && qmake && make -j $(nproc)
