name: Build RushHour App

on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      # These commands will run inside the docker container
      - name: Build Windows x64 static
        run: |
          docker login -u nathanesau -p b8a6929f67d3c3f84be9a77dc3d24b9123f935d6 docker.pkg.github.com
          docker pull docker.pkg.github.com/nathanesau/docker-qt/qt-win64s:1.0
          docker run --rm -it -v ${GITHUB_WORKSPACE}/src/app/cpp:/app docker.pkg.github.com/nathanesau/docker-qt/qt-win64s:1.0
          cp -r ${GITHUB_WORKSPACE}/src/app/cpp /app
          cd /app
          qmake
          make -j $(nproc)
